apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::975566413854:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1N8BVZ8I35CAL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::975566413854:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-24T14:12:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1563"
  uid: f717a3a6-8dc1-40d6-a9aa-4d2471620618
